#!/bin/bash

tmux -2 new-session -s NGINX -d 
tmux -2 new-window -n PSQL-main -c ~/Code/linux/packages/nginx vim
tmux split-window -h
tmux selectp -t 2
tmux split-window -v -c ~/Code/linux/packages/nginx/srv  #psql -U skelonl_admin -h 10.45.0.10 -d skelonl
tmux selectp -t 1 
tmux attach-session -t NGINX 

