#!/bin/bash

#. /opt/rh/rh-nginx18/enable
#. /opt/rh/rh-python34/enable

#CMD='sudo scl enable rh-nginx18 -- nginx'
ARGS='daemon off;error_log stderr info;'

sudo nginx -c /etc/nginx/nginx.conf -g "$ARGS" #> accesslog.txt 2>&1
